# SPDX-FileCopyrightText: 2025-present deepset GmbH <info@deepset.ai>
#
# SPDX-License-Identifier: Apache-2.0

from .custom_components import get_latest_custom_component_installation_logs, list_custom_component_installations
from .deployment import (
    activate_deployment,
    activate_deployment_revision,
    add_deployment_tag,
    create_deployment,
    create_deployment_revision,
    deactivate_deployment,
    delete_deployment,
    delete_deployment_tag,
    get_deployment,
    get_deployment_metrics,
    get_deployment_revision,
    get_deployment_stats,
    list_deployment_activity,
    list_deployment_revisions,
    list_deployment_tags,
    list_deployments,
    update_deployment,
)
from .doc_search import search_docs
from .haystack_service import (
    get_component_definition,
    get_custom_components,
    list_component_families,
    run_component,
    search_component_definition,
)
from .indexes import create_index, deploy_index, get_index, list_indexes, update_index, validate_index
from .model import get_models
from .object_store import (
    create_get_from_object_store,
    create_get_slice_from_object_store,
    create_grep_object_store,
    create_sed_object_store,
    create_yq_object_store,
)
from .pipeline import (
    create_pipeline,
    create_pipeline_version,
    debug_pipeline,
    deploy_pipeline,
    get_pipeline,
    get_pipeline_logs,
    get_pipeline_version,
    list_pipeline_versions,
    list_pipelines,
    patch_pipeline_version,
    restore_pipeline_version,
    search_pipeline,
    search_pipeline_with_filters,
    search_pipeline_with_params,
    validate_pipeline,
)
from .pipeline_template import get_template, list_templates, search_templates
from .search_history import (
    get_pipeline_trace,
    get_pipeline_trace_logs,
    get_pipeline_trace_span_tags,
    list_pipeline_search_history,
    list_pipeline_traces,
    list_search_history,
)
from .secrets import get_secret, list_secrets
from .skills import load_skill
from .workspace import create_workspace, get_workspace, list_workspaces

__all__ = [
    "list_custom_component_installations",
    "get_latest_custom_component_installation_logs",
    "search_docs",
    "run_component",
    "get_custom_components",
    "get_component_definition",
    "search_component_definition",
    "list_component_families",
    "list_indexes",
    "deploy_index",
    "update_index",
    "create_index",
    "get_index",
    "validate_index",
    "list_deployments",
    "list_deployment_tags",
    "create_deployment",
    "get_deployment",
    "update_deployment",
    "delete_deployment",
    "add_deployment_tag",
    "delete_deployment_tag",
    "list_deployment_revisions",
    "get_deployment_revision",
    "create_deployment_revision",
    "activate_deployment_revision",
    "activate_deployment",
    "deactivate_deployment",
    "list_deployment_activity",
    "get_deployment_metrics",
    "get_deployment_stats",
    "get_models",
    "create_get_from_object_store",
    "create_get_slice_from_object_store",
    "create_grep_object_store",
    "create_sed_object_store",
    "create_yq_object_store",
    "list_pipelines",
    "get_pipeline",
    "get_pipeline_logs",
    "debug_pipeline",
    "deploy_pipeline",
    "search_pipeline",
    "search_pipeline_with_filters",
    "search_pipeline_with_params",
    "create_pipeline",
    "validate_pipeline",
    "list_pipeline_versions",
    "create_pipeline_version",
    "get_pipeline_version",
    "patch_pipeline_version",
    "restore_pipeline_version",
    "list_templates",
    "get_template",
    "search_templates",
    "list_search_history",
    "list_pipeline_search_history",
    "list_pipeline_traces",
    "get_pipeline_trace",
    "get_pipeline_trace_span_tags",
    "get_pipeline_trace_logs",
    "get_secret",
    "list_secrets",
    "load_skill",
    "list_workspaces",
    "get_workspace",
    "create_workspace",
]
