[project]
name = "deepset-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.12",
    "mcp[cli]>=1.6.0",
    "requests>=2.32.3",
    "uvicorn>=0.34.2",
]

[project.scripts]
deepset-mcp = "deepset_mcp.main:launch_mcp"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
  "pytest"
]

[tool.pytest.ini_options]
testpaths = ["test"]


