name: Run CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Run tests
        run: make test-unit

  lint:
    name: Run Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Run lint
        run: make lint

      - name: Run format
        run: make format-check

  types:
    name: Run mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Run types
        run: make types

  license_headers:
    name: Check License Headers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check presence of license header
        run: docker run --rm -v "$(pwd):/github/workspace" ghcr.io/korandoru/hawkeye check

